
#w_pierre_groceries_manager_homepage:
#    path:     /
#    defaults: { _controller: WPierreGroceriesManagerBundle:GroceriesList:index }

groceriesmanager_controllers:
  resource: "@WPierreGroceriesManagerBundle/Controller/"
  type:     annotation
  prefix:   /